name: Data freshness
description: ""
tableName: fct_tasks
updatedAt: "2025-11-01T15:27:11.873Z"
metricQuery:
  exploreName: fct_tasks
  dimensions:
    - fct_tasks_updated_time_minute
  metrics: []
  filters:
    dimensions:
      id: ab945b78-65fc-4d4d-986f-c9c4038f8fe6
      and:
        - id: 9c1fd4fa-062b-45f1-af1c-1a81b504d504
          target:
            fieldId: fct_tasks_task_id
          values:
            - "0"
          operator: equals
          required: false
  sorts:
    - fieldId: fct_tasks_updated_time_minute
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations: []
  additionalMetrics:
    - name: updated_time_minute_max_of_updated_time_minute
      label: Max of Updated time minute
      description: "Max of Updated time minute on the table Fct tasks "
      uuid: c9378df4-1a66-4373-8cea-9b99ddddd47a
      sql: DATE_TRUNC(${TABLE}.updated_time, MINUTE)
      table: fct_tasks
      type: max
      baseDimensionName: updated_time_minute
      formatOptions:
        type: timestamp
        timeInterval: MINUTE
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Data last refreshed at
    flipColors: false
    selectedField: fct_tasks_updated_time_minute
    showComparison: false
    comparisonFormat: raw
    showBigNumberLabel: false
slug: data-freshness
tableConfig:
  columnOrder:
    - fct_tasks_updated_time_minute
spaceSlug: shared
version: 1
downloadedAt: "2025-11-01T15:27:19.958Z"
